import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { authContext, MyProvider } from "@/componentes/authProvider"

export default function RootLayout({ children }) {
  return (
    <MyProvider>
    <html lang="en">
      <head>
      <link rel="icon" type="image/png" href="/logo_tienda.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
    </MyProvider>
  )
}
